name: restaurant
description: RRS.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  go_router: ^12.1.1
  http: ^1.1.2
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/image/
    - assets/font/
    - assets/font/Exo/
    - assets/font/Exo/static/
    - .env.development

  fonts:
    - family: Exo
      fonts:
        - asset: assets/font/Exo/static/Exo2-ExtraBold.ttf
